### ISSUE TITLE
Polydex error 

### ISSUE THREAD

**Issue by fonkfader** [tomalbrc/tsa-decorations#2]
hi having an issue with latest version of TSA: Decorations & Furniture 2.0 :

[12:05:02] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "eu.pb4.polydex.api.v1.recipe.PolydexEntry.identifier()" because "polydexEntry" is null
	at de.tomalbrc.decorations.polydex.CarpentryPage.createPage(CarpentryPage.java:58) ~[tsa-decorations-2.0.0+1.21-1.21.1.jar:?]
	at dev.mattidragon.polydexbridge.PolydexBridge.createPacket(PolydexBridge.java:52) ~[polydex-bridge-1.0.1+mc.1.21.1.jar:?]
	at net.minecraft.class_3324.handler$cma000$polydex-bridge$syncPolyRecipesOnJoin(class_3324.java:6491) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:205) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.mixinextras$bridge$method_14570$39(class_8610.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.wrapOperation$dcc000$polymer-networking$polymerNet$prePlayHandshakeHackfest(class_8610.java:1038) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by tomalbrc** [comment]
Fixed in 2.0.1
